name:                hic-hac-hoe
version:             0.1.0.0
github:              "BlastWind/hic-hac-hoe"
license:             BSD3
author:              "Andrew Chen"
maintainer:          "andrewchen14250@gmail.com"
copyright:           "2022 Andrew Chen"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/BlastWind/hic-hac-hoe#readme>

dependencies:
- base >= 4.7 && < 5
- brick
- vty

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hic-hac-hoe-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hic-hac-hoe

tests:
  hic-hac-hoe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hic-hac-hoe
